name: Build and GH-Page Deploy

env:
  TEAM_ID: ${{ vars.TEAM_ID }}
  LEAGUE_ID: ${{ vars.LEAGUE_ID }}
  TEAM_NAME: ${{ vars.TEAM_NAME }}
  TEAM_DESCRIPTION: ${{ vars.TEAM_DESCRIPTION }}
  LOGO_FILE: ${{ vars.LOGO_FILE }}
  BEER_RULES_MD_FILE: ${{ vars.BEER_RULES_MD_FILE }}

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Install
        run: npm install

      - name: Build
        run: |
          npm run build

      - name: Deploy to GH Page
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: www
          ssh-key: ${{ secrets.DEPLOY_KEY }}
          